src/MedicLabUserManager/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  resources :roles
  resources :users
  resources :drugs
  root "index#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

src/MedicLabUserManager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

src/MedicLabUserManager/app/models/drug.rb
class Drug < ApplicationRecord
    has_many :perscription_drugs
    has_many :perscriptions, :through => :perscription_drugs, :dependent => :destroy
    validates :name, :description, presence: true
end

src/MedicLabUserManager/app/models/perscription.rb
class Perscription < ApplicationRecord
    belongs_to :examination
    has_many :drugs, through: :perscription_drugs
    has_many :perscription_drugs,:dependent => :destroy
end

src/MedicLabUserManager/app/models/perscription_drug.rb
class PerscriptionDrug < ApplicationRecord
    belongs_to :perscription
    belongs_to :drug
    validates :usageDescription, presence: true
end

src/MedicLabUserManager/app/models/role.rb
class Role < ApplicationRecord
    has_many :users
    validates :name, :description, presence: true
end

src/MedicLabUserManager/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  validates :first_name, :last_name, :address, :dob, :username, :email,:password,  presence: true, on: :create
  def active_for_authentication? 
    super && is_admin?
  end

  def inactive_message
    active_for_authentication? ? super : :unauthorized_role
  end

  def is_admin?
     role.name == "Admin" 
  end
end

src/MedicLabUserManager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

src/MedicLabUserManager/app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_drug, only: %i[ show edit update destroy ]


  # GET /drugs or /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1 or /drugs/1.json
  def show

  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs or /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to drug_url(@drug), notice: "Drug was successfully created." }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1 or /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to drug_url(@drug), notice: "Drug was successfully updated." }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1 or /drugs/1.json
  def destroy
    @drug.destroy

    respond_to do |format|
      format.html { redirect_to drugs_url, alert: "Drug was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def drug_params
      params.require(:drug).permit(:name, :description)
    end
end

src/MedicLabUserManager/app/controllers/index_controller.rb
class IndexController < ApplicationController
end

src/MedicLabUserManager/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_role, only: %i[ show edit update destroy ]

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, alert: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

src/MedicLabUserManager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, alert: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :address, :dob, :username, :email, :password,:password_confirmation, :role_id)
    end
end

src/MedicLabUserManager/app/helpers/application_helper.rb
module ApplicationHelper
end

src/MedicLabUserManager/app/helpers/index_helper.rb
module IndexHelper
end

src/MedicLabUserManager/app/helpers/roles_helper.rb
module RolesHelper
end

src/MedicLabUserManager/app/helpers/users_helper.rb
module UsersHelper
end

src/MedicLabUserManager/app/views/drugs/_drug.html.erb
<div id="<%= dom_id drug %>">
  
  <p>
    <strong>Name:</strong>
    <%= drug.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= drug.description %>
  </p>
</div>

src/MedicLabUserManager/app/views/drugs/_form.html.erb
<%= form_with(model: drug) do |form| %>
  <% if drug.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
        <% drug.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.text_field :name, class:"form-control", placeholder: "Drug Name" %>
  </div>

  <div class="form-group mb-2">
    <%= form.text_area :description, class:"form-control", placeholder: "Description" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

src/MedicLabUserManager/app/views/drugs/edit.html.erb
<h1>Editing drug</h1>

<%= render "form", drug: @drug %>

<br>

<div>
  <%= link_to "Show this drug", @drug, class:"btn btn-primary" %> |
  <%= link_to "Back to drugs", drugs_path, class:"btn btn-secondary" %>
</div>

src/MedicLabUserManager/app/views/drugs/index.html.erb
<h1>Drugs</h1>

<div id="drugs">
  <% @drugs.each do |drug| %>
    <%= render drug %>
    <p>
      <%= link_to "Show this drug", drug, class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "New drug", new_drug_path, class:"btn btn-success" %>

src/MedicLabUserManager/app/views/drugs/new.html.erb
<h1>New drug</h1>

<%= render "form", drug: @drug %>

<br>

<div>
  <%= link_to "Back to drugs", drugs_path, class:"btn btn-secondary" %>
</div>

src/MedicLabUserManager/app/views/drugs/show.html.erb
<%= render @drug %>

<div>
  <%= link_to "Edit this drug", edit_drug_path(@drug), class:"btn btn-success" %> |
  <%= link_to "Back to drugs", drugs_path, class:"btn btn-secondary" %>

  <%= button_to "Destroy this drug", @drug, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger mt-3" %>
</div>

src/MedicLabUserManager/app/views/index/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'MedicLab', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link active"%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in?  %>
        
        <li class="nav-item">
              <%= link_to "New Role", new_role_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
              <%= link_to "New Drug", new_drug_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Create User', new_user_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'View profiles', users_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-dark", style:"border-color: white" %>
        </li>
      </ul>
            <% else %>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-dark", style:"border-color: white"%>
        </li>
      </ul>

            <% end %>
    </div>
  </div>
</nav>

src/MedicLabUserManager/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>MedicLabUserManagement</title>
  </head>
  <body>
    <%= render 'index/header'%>

    <div class="container">
    
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      </br>
    <%= yield %>

    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

src/MedicLabUserManager/app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="form-group mb-2">
    <%= form.text_field :name, class:"form-control", placeholder: "Please enter a Role name"  %>
  </div>

  <div  class="form-group mb-2">
    <%= form.text_field :description, class:"form-control", placeholder: "Description"  %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success mb-3" %>
  </div>
<% end %>

src/MedicLabUserManager/app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= role.description %>
  </p>

</div>

src/MedicLabUserManager/app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role, class:"btn btn-primary" %> |
  <%= link_to "Back to roles", roles_path, class:"btn btn-secondary" %>
</div>

src/MedicLabUserManager/app/views/roles/index.html.erb
<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role, class:"btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path, class:"btn btn-success" %>

src/MedicLabUserManager/app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>


<div>
  <%= link_to "Back to roles", roles_path, class:"btn btn-secondary" %>
</div>

src/MedicLabUserManager/app/views/roles/show.html.erb
<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role), class:"btn btn-success" %> |
  <%= link_to "Back to roles", roles_path, class:"btn btn-secondary" %>

  <%= button_to "Destroy this role", @role, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger mt-3" %>
</div>

src/MedicLabUserManager/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, class:"form-control" %>
  </div>
<% if !@user.persisted? %>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, autocomplete: "new-password", class:"form-control", placeholder:"Password must be 6 characters minimum" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation, autocomplete: "new-password", class:"form-control", placeholder:"You must repeat Password" %>
  </div>

<% end %>
  <div class="form-group">
    <%= form.label :roles_id, style: "display: block" %>
    <%= form.collection_select :role_id, Role.order(:name),:id,:name, {:prompt => "Please select a Role", :selected => @user.role_id }, class:"form-control" %>
  </div>

  <div>
  <br/>
    <%= form.submit class:"btn btn-success mb-2" %>
  </div>
<% end %>

src/MedicLabUserManager/app/views/users/_user.html.erb
      <th scope="row"><%= user.id%></th>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.address %></td>
      <td><%= user.dob %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.role.name %></td>

src/MedicLabUserManager/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<div>
  <%= link_to "Show this user", @user , class:"btn btn-primary" %> |
  <%= link_to "Back to users", users_path, class:"btn btn-secondary"  %>
</div>

src/MedicLabUserManager/app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <table class="table table-striped table-hover table-bordered text-break " style="width:100%;">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Address</th>
      <th scope="col">Dateofbirth</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <%= render user %>
      <td><%= link_to "Show this user", user, class:"btn btn-primary" %></td>
    </tr>
  <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New user", new_user_path, class:"btn btn-success"%>

src/MedicLabUserManager/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>


<div>
  <%= link_to "Back to users", users_path , class:"btn btn-secondary"%>
</div>

src/MedicLabUserManager/app/views/users/show.html.erb
<%= render @user %>


<div>
  <%= link_to "Edit this user", edit_user_path(@user), class:"btn btn-success" %> |
  <%= link_to "Back to users", users_path, class:"btn btn-secondary" %>

  <%= button_to "Destroy this user", @user, method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger mt-3" %>
</div>